import { Country, Curriculum, Subject, Teacher, PricingPlan, Testimonial, FAQItem } from "@/types";

export const SAAY_COUNTRIES: Country[] = [
  {
    id: "ksa",
    name: "المملكة العربية السعودية",
    code: "SA",
    flag: "🇸🇦",
    curricula: ["national-sa", "american", "british", "ib"],
  },
  {
    id: "uae",
    name: "الإمارات العربية المتحدة",
    code: "AE",
    flag: "🇦🇪",
    curricula: ["national-ae", "british", "american", "ib"],
  },
  {
    id: "qatar",
    name: "دولة قطر",
    code: "QA",
    flag: "🇶🇦",
    curricula: ["national-qa", "british", "american", "ib"],
  },
  {
    id: "kuwait",
    name: "دولة الكويت",
    code: "KW",
    flag: "🇰🇼",
    curricula: ["national-kw", "american", "british", "ib"],
  },
  {
    id: "egypt",
    name: "جمهورية مصر العربية",
    code: "EG",
    flag: "🇪🇬",
    curricula: ["national-eg", "languages-eg", "british", "american", "stem"],
  },
  {
    id: "oman",
    name: "سلطنة عُمان",
    code: "OM",
    flag: "🇴🇲",
    curricula: ["national-om", "british", "ib"],
  },
  {
    id: "bahrain",
    name: "مملكة البحرين",
    code: "BH",
    flag: "🇧🇭",
    curricula: ["national-bh", "british", "american"],
  },
];

export const SAAY_CURRICULA: Curriculum[] = [
  {
    id: "national-sa",
    name: "المنهج السعودي (الوزاري والأهلي)",
    enName: "Saudi National Curriculum",
    description: "مقررات وزارة التعليم السعودية لجميع المراحل واختبارات القدرات والتحصيلي",
    grades: ["الابتدائي", "المتوسط", "الثانوي (مسارات)", "القدرات والتحصيلي"],
  },
  {
    id: "british",
    name: "المنهج البريطاني (IGCSE / GCSE / A-Levels)",
    enName: "British Curriculum (Cambridge / Edexcel / Oxford)",
    description: "شرح شامل ومراجعة Past Papers لمختلف مجالس الامتحانات البريطانية",
    grades: ["Key Stage 2 & 3", "Year 10 - 11 (IGCSE/GCSE)", "Year 12 - 13 (AS & A-Levels)"],
  },
  {
    id: "american",
    name: "المنهج الأمريكي (American Diploma & AP & SAT)",
    enName: "American Curriculum & Advanced Placement",
    description: "تغطية معايير Common Core، ودروس متقدمة في AP و SAT / ACT",
    grades: ["Elementary (Grades 1-5)", "Middle School (Grades 6-8)", "High School (Grades 9-12)", "AP & SAT Prep"],
  },
  {
    id: "ib",
    name: "البكالوريا الدولية (IB - PYP, MYP, DP)",
    enName: "International Baccalaureate",
    description: "تدريس متخصص لمواد IB Diploma (HL & SL) ومساعدة في IA و EE",
    grades: ["Primary Years (PYP)", "Middle Years (MYP)", "Diploma Programme (DP1 & DP2)"],
  },
  {
    id: "national-ae",
    name: "المنهج الإماراتي الوزاري",
    enName: "UAE Ministry of Education Curriculum",
    description: "شامل مسارات النخبة، المتقدم، والعام واختبارات EmSAT",
    grades: ["الحلقة الأولى", "الحلقة الثانية", "الحلقة الثالثة (الثانوي)", "امتحانات EmSAT"],
  },
  {
    id: "national-eg",
    name: "المنهج المصري واللغات",
    enName: "Egyptian National & Languages",
    description: "المناهج المطورة واللغات والتأسيس للثانوية العامة",
    grades: ["المرحلة الابتدائية", "المرحلة الإعدادية", "المرحلة الثانوية"],
  },
];

export const SAAY_SUBJECTS: Subject[] = [
  { id: "math", name: "الرياضيات (Mathematics)", enName: "Mathematics", category: "math", iconName: "Calculator" },
  { id: "physics", name: "الفيزياء (Physics)", enName: "Physics", category: "science", iconName: "Atom" },
  { id: "chemistry", name: "الكيمياء (Chemistry)", enName: "Chemistry", category: "science", iconName: "FlaskConical" },
  { id: "biology", name: "الأحياء والعلوم (Biology & Science)", enName: "Biology", category: "science", iconName: "Dna" },
  { id: "english", name: "اللغة الإنجليزية (English Language)", enName: "English", category: "languages", iconName: "BookA" },
  { id: "arabic", name: "اللغة العربية والتأسيس اللغوي", enName: "Arabic", category: "languages", iconName: "BookOpen" },
  { id: "gat-saat", name: "القدرات العامة والتحصيلي", enName: "GAT & SAAT", category: "exam-prep", iconName: "GraduationCap" },
  { id: "cs-coding", name: "الحاسب الآلي والبرمجة", enName: "Computer Science", category: "general", iconName: "Code2" },
];

export const SAAY_TEACHERS: Teacher[] = [
  {
    id: "t1",
    name: "د. عبد الرحمن الشهري",
    title: "معلم أول رياضيات وفيزياء - معتمد من موهبة وكامبريدج",
    initials: "د.ع",
    experienceYears: 12,
    rating: 4.98,
    reviewsCount: 142,
    completedSessions: 890,
    hourlyRate: 140,
    currency: "SAR",
    subjects: ["الرياضيات (Mathematics)", "الفيزياء (Physics)", "القدرات العامة والتحصيلي"],
    curricula: ["national-sa", "british", "american"],
    countries: ["ksa", "uae", "qatar"],
    bio: "خبرة أكثر من 12 عاماً في مدارس الرياض وتدريس مناهج كامبريدج. متخصص في حل تجميعات الاختبارات الوزارية وتأسيس التفكير الرياضي السليم وتجاوز صعوبات المفاهيم المجردة.",
    verified: true,
    featuredBadge: "الأعلى تقييماً في الرياضيات والقدرات",
    nextAvailable: "اليوم 6:00 م",
  },
  {
    id: "t2",
    name: "أ. مريم المنصوري",
    title: "أخصائية كيمياء وأحياء - ماجستير المناهج البريطانية IGCSE & IB",
    initials: "أ.م",
    experienceYears: 9,
    rating: 4.95,
    reviewsCount: 118,
    completedSessions: 720,
    hourlyRate: 155,
    currency: "SAR",
    subjects: ["الكيمياء (Chemistry)", "الأحياء والعلوم (Biology & Science)"],
    curricula: ["british", "ib", "national-ae"],
    countries: ["uae", "qatar", "ksa"],
    bio: "معلمة معتمدة لشهادات IGCSE و IB DP بخبرة 9 سنوات في مدارس دبي. تركز على التجارب المعملية الرقمية وحل أسئلة الامتحانات السابقة (Past Papers) بدقة وفق معايير التصحيح الرسمية.",
    verified: true,
    featuredBadge: "معلمة نخبة لـ IGCSE & IB",
    nextAvailable: "غداً 4:30 م",
  },
  {
    id: "t3",
    name: "أ. طارق عبد العزيز",
    title: "مدرب معتمد لاختبارات قياس (قدرات وتحصيلي) و SAT",
    initials: "أ.ط",
    experienceYears: 11,
    rating: 4.97,
    reviewsCount: 165,
    completedSessions: 1140,
    hourlyRate: 130,
    currency: "SAR",
    subjects: ["الرياضيات (Mathematics)", "القدرات العامة والتحصيلي", "اللغة الإنجليزية (English Language)"],
    curricula: ["american", "national-sa", "national-eg"],
    countries: ["ksa", "egypt", "kuwait"],
    bio: "متخصص في استراتيجيات الحل الذهني السريع وإدارة وقت الاختبار. حقق أكثر من 85% من طلابه درجات تفوق 95% في اختبارات القدرات العامة و SAT.",
    verified: true,
    featuredBadge: "خبير التجميعات واختبارات قياس",
    nextAvailable: "اليوم 8:00 م",
  },
  {
    id: "t4",
    name: "أ. سارة الهاشمي",
    title: "معلمة لغة إنجليزية وأدب - معتمدة من المجلس الثقافي البريطاني (IELTS)",
    initials: "أ.س",
    experienceYears: 8,
    rating: 4.99,
    reviewsCount: 96,
    completedSessions: 530,
    hourlyRate: 145,
    currency: "SAR",
    subjects: ["اللغة الإنجليزية (English Language)"],
    curricula: ["british", "american", "ib"],
    countries: ["qatar", "uae", "kuwait", "ksa"],
    bio: "خبرة 8 سنوات في تطوير مهارات الكتابة الأكاديمية والتحليل الأدبي للغة الإنجليزية وتأهيل الطلاب لتحقيق درجات 7.5+ في اختبارات IELTS ومتطلبات الجامعات العالمية.",
    verified: true,
    featuredBadge: "أخصائية IELTS & Academic Writing",
    nextAvailable: "غداً 5:00 م",
  },
];

export const SAAY_PRICING_PLANS: PricingPlan[] = [
  {
    id: "trial",
    name: "الحصة الاستكشافية",
    subtitle: "حصة فردية كاملة للتعرف على أسلوب المعلم وتشخيص مستوى الطالب",
    pricePerSession: 85,
    totalPrice: 85,
    currency: "ر.س",
    sessionsCount: 1,
    discountPercentage: 40,
    features: [
      "حصة فردية كاملة 1-on-1 (60 دقيقة)",
      "تشخيص المستوى الأكاديمي وتحديد خطة العمل",
      "تسجيل الحصة بالكامل بجودة فائقة",
      "تقرير تحليلي فوري لولي الأمر بعد الحصة",
      "ضمان استرداد الرضا 100% بدون أي قيود",
    ],
    ctaText: "احجز حصتك التجريبية الآن",
  },
  {
    id: "growth",
    name: "باقة التفوّق الشهري",
    subtitle: "الخيار الأنسب لمتابعة دراسية مستمرة بمعدل حصتين أسبوعياً",
    badge: "الباقة الأكثر طلباً وتفضيلاً",
    pricePerSession: 110,
    totalPrice: 880,
    currency: "ر.س",
    sessionsCount: 8,
    popular: true,
    discountPercentage: 25,
    features: [
      "8 حصص فردية تفاعلية 1-on-1 (60 دقيقة لكل حصة)",
      "تثبيت جدول المواعيد والمعلم المفضل",
      "تقارير أداء وتطور أسبوعية تصل لولي الأمر",
      "وصول دائم لجميع تسجيلات وملاحظات الحصص",
      "متابعة مستمرة مع المنسق الأكاديمي عبر واتساب",
      "مرونة كاملة في إعادة جدولة المواعيد",
    ],
    ctaText: "اشترك في باقة التفوّق",
  },
  {
    id: "mastery",
    name: "باقة التميّز الفصلي",
    subtitle: "تغطية شاملة للمنهج ومراجعات مكثفة قبل الاختبارات النهائية",
    badge: "أعلى توفير فصلي",
    pricePerSession: 95,
    totalPrice: 2280,
    currency: "ر.س",
    sessionsCount: 24,
    discountPercentage: 35,
    features: [
      "24 حصة فردية تفاعلية تغطي الفصل الدراسي كاملاً",
      "خطة مخصصة تناسب مواعيد الاختبارات المدرسية",
      "مراجعات مكثفة وحل اختبارات سابقة ونماذج امتحانات",
      "منسق أكاديمي خاص للإشراف والمتابعة المستمرة",
      "تقارير تقدم شهرية ومناقشة مباشرة مع ولي الأمر",
      "أولوية مطلقة في حجز أوقات الذروة والمراجعات",
    ],
    ctaText: "ابدأ خطة التميز الفصلي",
  },
];

export const SAAY_TESTIMONIALS: Testimonial[] = [
  {
    id: "rev1",
    name: "خالد السبيعي",
    role: "ولي أمر",
    location: "الرياض",
    countryFlag: "🇸🇦",
    curriculum: "المنهج السعودي - مسارات ثانوي",
    grade: "ثاني ثانوي",
    subject: "الرياضيات والقدرات",
    rating: 5,
    content: "المعلم كان ممتازاً جداً في تأسيس ابني في القسم الكمي للقدرات وتوضيح القوانين بطريقة سهلة. الميزة الأكبر بالنسبة لي كولي أمر كانت وضوح تقارير كل حصة وإمكانية مراجعة التسجيل قبل الاختبار الشهري.",
    improvementText: "ارتفعت درجة الطالب من 76% إلى 94% في الاختبار الفصلي",
  },
  {
    id: "rev2",
    name: "نادية الشامسي",
    role: "ولي أمر",
    location: "دبي",
    countryFlag: "🇦🇪",
    curriculum: "المنهج البريطاني (IGCSE)",
    grade: "Year 11",
    subject: "Physics & Chemistry",
    rating: 5,
    content: "ابنتي كانت تعاني مع Past Papers الكيمياء والفيزياء في كامبريدج. المعلمة في سَعى فاهمة للمنهج بدقة وطريقة حل الأسئلة خلت البنت واثقة تماماً من دخول الامتحان التجريبي.",
    improvementText: "حققت تقدير A* في اختبارات كامبريدج التجريبية",
  },
  {
    id: "rev3",
    name: "فيصل الكواري",
    role: "طالب",
    location: "الدوحة",
    countryFlag: "🇶🇦",
    curriculum: "البكالوريا الدولية (IB DP)",
    grade: "DP2",
    subject: "Mathematics HL",
    rating: 5,
    content: "كنت محتاج تدريب عميق على Math HL وتوجيه في خطوات الحل المنطقي. الأستاذ ساعدني بطريقة مباشرة ومرتبة وراجعنا أغلب الأفكار المعقدة في وقت قياسي.",
    improvementText: "حصل على الدرجة 7 في تقييم الرياضيات IB",
  },
  {
    id: "rev4",
    name: "أميرة منصور",
    role: "ولي أمر",
    location: "القاهرة الجديدة",
    countryFlag: "🇪🇬",
    curriculum: "المنهج الأمريكي (SAT & AP)",
    grade: "Grade 11",
    subject: "SAT Math & English",
    rating: 5,
    content: "المنصة منظمة والدعم متعاون وسريع في الرد. جدول الحصص مرن ويتناسب مع جدول ابني في المدرسة، والمعلم ساعده بشكل ملحوظ في رفع سرعة الحل في قسم الرياضيات.",
    improvementText: "رفع سكور الـ SAT بمقدار 210 نقطة",
  },
];

export const SAAY_FAQS: FAQItem[] = [
  {
    id: "faq1",
    question: "كيف يتم اختيار واعتماد المعلمين في أكاديمية سَعى؟",
    answer: "نتبع في سَعى معايير فحص واختيار صارمة جداً؛ حيث نقبل أقل من 5% من المتقدمين بعد التحقق الدقيق من مؤهلاتهم الأكاديمية وخبراتهم في مناهج محددة، واجتياز اختبار تدريسي تفاعلي حقيقي ومقابلات تقييم الأسلوب والشغف التعليمي.",
    category: "teachers",
  },
  {
    id: "faq2",
    question: "هل الحصص تكون فردية أم جماعية؟",
    answer: "جميع حصص سَعى هي حصص فردية خاصة 1-on-1 (طالب واحد مع معلم واحد) لضمان التركيز الكامل بنسبة 100%، وتخصيص الشرح وسرعة التدريس وفق الاحتياج الفعلي للطالب دون أي تشتيت.",
    category: "booking",
  },
  {
    id: "faq3",
    question: "ماذا لو كانت دولتي أو منهجي الدراسي غير مدرج في القائمة؟",
    answer: "في سَعى نؤمن بأن احتياج الطالب يأتي أولاً. يمكنك الضغط على 'طلب منسق أكاديمي' أو التواصل معنا عبر واتساب، وسيقوم فريق المنسقين الأكاديميين بتوفير معلم معتمد ومطابق لمنهجك ودولتك فوراً.",
    category: "curriculum",
  },
  {
    id: "faq4",
    question: "كيف يستطيع ولي الأمر متابعة مستوى ابنه؟",
    answer: "يحصل ولي الأمر على تقرير أداء تفصيلي بعد كل حصة يوضح مدى استيعاب الطالب، الواجبات، ونقاط القوة والتحسين، بالإضافة إلى إمكانية مشاهدة تسجيل الحصة بالكامل في أي وقت ومتابعة جدول الحصص القادمة.",
    category: "parents",
  },
  {
    id: "faq5",
    question: "هل يمكنني تغيير موعد الحصة أو إعادة جدولتها؟",
    answer: "نعم بكل سهولة، تتيح لك المنصة إعادة جدولة الموعد قبل وقت الحصة بمرونة كاملة عبر حسابك أو بالتنسيق المباشر مع المعلم وفريق الدعم دون أي تعقيد.",
    category: "booking",
  },
  {
    id: "faq6",
    question: "ما هي سياسة الاسترداد وضمان الرضا؟",
    answer: "نحن نضمن رضاك التام عن التجربة التعليمية. إذا لم تكن راضياً عن الحصة الاستكشافية الأولى لأي سبب، نعيد لك المبلغ بالكامل أو نوفر لك حصة بديلة مع معلم آخر فوراً وبكل ترحيب.",
    category: "pricing",
  },
];
