import { Country, Curriculum, Subject, Teacher, PricingPlan, Testimonial, FAQItem } from "@/types";

export const SAAY_COUNTRIES: Country[] = [
  {
    id: "egypt",
    name: "جمهورية مصر العربية",
    code: "EG",
    flag: "🇪🇬",
    curricula: ["national-eg", "languages-eg", "british", "american", "stem", "ib"],
  },
  {
    id: "uae",
    name: "الإمارات العربية المتحدة",
    code: "AE",
    flag: "🇦🇪",
    curricula: ["national-ae", "british", "american", "ib"],
  },
];

export const SAAY_CURRICULA: Curriculum[] = [
  {
    id: "national-eg",
    name: "المنهج المصري (العام واللغات والتجريبي)",
    enName: "Egyptian National & Languages Curriculum",
    description: "مقررات وزارة التربية والتعليم المصرية لجميع المراحل والتأسيس للثانوية العامة والشهادة الإعدادية",
    grades: ["المرحلة الابتدائية", "المرحلة الإعدادية", "الثانوية العامة (عام ولغات)"],
  },
  {
    id: "national-ae",
    name: "المنهج الإماراتي الوزاري (العام والمتقدم والنخبة)",
    enName: "UAE Ministry of Education Curriculum",
    description: "شامل مسارات النخبة، المتقدم، والعام، واختبارات قياس الكفاءة التربوية EmSAT",
    grades: ["الحلقة الأولى (1-4)", "الحلقة الثانية (5-8)", "الحلقة الثالثة (الثانوي 9-12)", "امتحانات EmSAT"],
  },
  {
    id: "british",
    name: "المنهج البريطاني (IGCSE / GCSE / A-Levels)",
    enName: "British International Curriculum (Cambridge / Edexcel / Oxford)",
    description: "شرح شامل وتدريب مكثف على Past Papers لمختلف مجالس الامتحانات في مصر والإمارات",
    grades: ["Key Stage 2 & 3", "Year 10 - 11 (IGCSE/GCSE)", "Year 12 - 13 (AS & A-Levels)"],
  },
  {
    id: "american",
    name: "المنهج الأمريكي (American Diploma & SAT / EST / AP)",
    enName: "American Curriculum & Advanced Placement",
    description: "تغطية معايير الدبلومة الأمريكية والتحضير لاختبارات SAT و EST و ACT و AP",
    grades: ["Elementary School", "Middle School", "High School (Grades 9-12)", "SAT & EST Prep"],
  },
  {
    id: "ib",
    name: "البكالوريا الدولية (IB - PYP, MYP, DP)",
    enName: "International Baccalaureate",
    description: "تدريس متخصص لمواد IB Diploma (HL & SL) والإشراف على IA و Extended Essay",
    grades: ["Primary Years (PYP)", "Middle Years (MYP)", "Diploma Programme (DP1 & DP2)"],
  },
  {
    id: "stem",
    name: "مدارس المتفوقين STEM ومدارس النيل الدولية",
    enName: "STEM Schools & Nile International",
    description: "تدريس المناهج المتطورة لمادتي العلوم والرياضيات والمشروعات التطبيقية Capstone",
    grades: ["الصف الأول الثانوي STEM", "الصف الثاني الثانوي STEM", "الصف الثالث الثانوي STEM"],
  },
];

export const SAAY_SUBJECTS: Subject[] = [
  { id: "math", name: "الرياضيات (Mathematics & Mechanics)", enName: "Mathematics", category: "math", iconName: "Calculator" },
  { id: "physics", name: "الفيزياء (Physics)", enName: "Physics", category: "science", iconName: "Atom" },
  { id: "chemistry", name: "الكيمياء (Chemistry)", enName: "Chemistry", category: "science", iconName: "FlaskConical" },
  { id: "biology", name: "الأحياء والعلوم (Biology & Science)", enName: "Biology", category: "science", iconName: "Dna" },
  { id: "english", name: "اللغة الإنجليزية (English Language & Literature)", enName: "English", category: "languages", iconName: "BookA" },
  { id: "arabic", name: "اللغة العربية والنحو والبلاغة", enName: "Arabic", category: "languages", iconName: "BookOpen" },
  { id: "exam-prep", name: "اختبارات المعادلات والقبول (EmSAT, SAT, EST)", enName: "Standardized Tests", category: "exam-prep", iconName: "GraduationCap" },
  { id: "cs-coding", name: "الحاسب الآلي والبرمجة (Computer Science)", enName: "Computer Science", category: "general", iconName: "Code2" },
];

export const SAAY_TEACHERS: Teacher[] = [
  {
    id: "t1",
    name: "د. عبد الرحمن زهران",
    title: "كبير معلمي الرياضيات والفيزياء - خبير IGCSE والثانوية العامة",
    initials: "د.ع",
    experienceYears: 13,
    rating: 4.98,
    reviewsCount: 156,
    completedSessions: 940,
    hourlyRate: 140,
    currency: "درهم / ج.م",
    subjects: ["الرياضيات (Mathematics & Mechanics)", "الفيزياء (Physics)", "اختبارات المعادلات والقبول (EmSAT, SAT, EST)"],
    curricula: ["national-eg", "british", "national-ae", "american"],
    countries: ["egypt", "uae"],
    bio: "خبرة أكثر من 13 عاماً في كبرى المدارس الدولية في القاهرة ودبي. متخصص في تبسيط المفاهيم الرياضية المعقدة وحل اختبارات كامبريدج وإدكسل ونماذج الثانوية العامة والـ EmSAT بأعلى معايير الدقة.",
    verified: true,
    featuredBadge: "الأعلى تقييماً في الرياضيات والفيزياء",
    nextAvailable: "اليوم 6:00 م",
  },
  {
    id: "t2",
    name: "أ. مريم المنصوري",
    title: "أخصائية كيمياء وأحياء - ماجستير المناهج البريطانية IGCSE & IB",
    initials: "أ.م",
    experienceYears: 9,
    rating: 4.96,
    reviewsCount: 124,
    completedSessions: 780,
    hourlyRate: 150,
    currency: "درهم / ج.م",
    subjects: ["الكيمياء (Chemistry)", "الأحياء والعلوم (Biology & Science)"],
    curricula: ["british", "ib", "national-ae"],
    countries: ["uae", "egypt"],
    bio: "معلمة معتمدة لشهادات IGCSE و IB DP في مدارس دبي وأبوظبي. تركيز كامل على فهم التجارب المعملية والتدريب على أسئلة الامتحانات الرسمية ومساعدة الطلاب على تحصيل درجات 8 و 9 و A*.",
    verified: true,
    featuredBadge: "معلمة نخبة لـ IGCSE & IB",
    nextAvailable: "غداً 4:30 م",
  },
  {
    id: "t3",
    name: "أ. طارق عبد العزيز",
    title: "مدرب معتمد لاختبارات SAT و EST و EmSAT والرياضيات المتقدمة",
    initials: "أ.ط",
    experienceYears: 11,
    rating: 4.97,
    reviewsCount: 168,
    completedSessions: 1190,
    hourlyRate: 135,
    currency: "درهم / ج.م",
    subjects: ["الرياضيات (Mathematics & Mechanics)", "اختبارات المعادلات والقبول (EmSAT, SAT, EST)", "اللغة الإنجليزية (English Language & Literature)"],
    curricula: ["american", "national-eg", "national-ae"],
    countries: ["egypt", "uae"],
    bio: "متخصص في استراتيجيات الحل السريع وإدارة وقت الامتحان لطلاب الدبلومة الأمريكية والمنهج الإماراتي المتقدم. حقق أكثر من 88% من طلابه درجات متقدمة تؤهلهم لأفضل كليات الهندسة والطب.",
    verified: true,
    featuredBadge: "خبير SAT & EST & EmSAT",
    nextAvailable: "اليوم 8:00 م",
  },
  {
    id: "t4",
    name: "أ. سارة الشريف",
    title: "معلمة لغة إنجليزية وأدب - معتمدة من المجلس الثقافي البريطاني (IELTS & IGCSE)",
    initials: "أ.س",
    experienceYears: 8,
    rating: 4.99,
    reviewsCount: 104,
    completedSessions: 580,
    hourlyRate: 130,
    currency: "درهم / ج.م",
    subjects: ["اللغة الإنجليزية (English Language & Literature)"],
    curricula: ["british", "american", "ib", "national-eg", "national-ae"],
    countries: ["egypt", "uae"],
    bio: "خبرة 8 سنوات في تدريس الإنجليزية الأكاديمية واللغات والتحضير لـ IELTS و IGCSE English في الإسكندرية والشارقة. أسلوب تفاعلي لصقل مهارات التعبير الكتابي والتحليل الأدبي بطلاقة.",
    verified: true,
    featuredBadge: "أخصائية IELTS & Academic English",
    nextAvailable: "غداً 5:00 م",
  },
];

export const SAAY_PRICING_PLANS: PricingPlan[] = [
  {
    id: "trial",
    name: "الحصة الاستكشافية",
    subtitle: "حصة فردية كاملة للتعرف على أسلوب المعلم وتشخيص مستوى الطالب",
    pricePerSession: 85,
    totalPrice: 85,
    currency: "حسب الدولة",
    sessionsCount: 1,
    features: [
      "حصة فردية كاملة 1-on-1 (60 دقيقة)",
      "تشخيص المستوى الأكاديمي وتحديد خطة العمل",
      "تسجيل الحصة بالكامل بجودة فائقة",
      "تقرير تحليلي فوري لولي الأمر بعد الحصة",
      "ضمان استرداد الرضا 100% بدون أي قيود",
    ],
    ctaText: "احجز حصتك التجريبية الآن",
  },
  {
    id: "growth",
    name: "باقة التفوّق الشهري",
    subtitle: "الخيار الأنسب لمتابعة دراسية مستمرة بمعدل حصتين أسبوعياً",
    badge: "الباقة الأكثر طلباً وتفضيلاً",
    pricePerSession: 110,
    totalPrice: 880,
    currency: "حسب الدولة",
    sessionsCount: 8,
    popular: true,
    features: [
      "8 حصص فردية تفاعلية 1-on-1 (60 دقيقة لكل حصة)",
      "تثبيت جدول المواعيد والمعلم المفضل",
      "تقارير أداء وتطور أسبوعية تصل لولي الأمر",
      "وصول دائم لجميع تسجيلات وملاحظات الحصص",
      "متابعة مستمرة مع المنسق الأكاديمي عبر واتساب",
      "مرونة كاملة في إعادة جدولة المواعيد",
    ],
    ctaText: "اشترك في باقة التفوّق",
  },
  {
    id: "mastery",
    name: "باقة التميّز الفصلي",
    subtitle: "تغطية شاملة للمنهج ومراجعات مكثفة قبل الاختبارات النهائية",
    badge: "أعلى توفير فصلي",
    pricePerSession: 95,
    totalPrice: 2280,
    currency: "حسب الدولة",
    sessionsCount: 24,
    features: [
      "24 حصة فردية تفاعلية تغطي الفصل الدراسي كاملاً",
      "خطة مخصصة تناسب مواعيد الاختبارات المدرسية",
      "مراجعات مكثفة وحل اختبارات سابقة ونماذج امتحانات",
      "منسق أكاديمي خاص للإشراف والمتابعة المستمرة",
      "تقارير تقدم شهرية ومناقشة مباشرة مع ولي الأمر",
      "أولوية مطلقة في حجز أوقات الذروة والمراجعات",
    ],
    ctaText: "ابدأ خطة التميز الفصلي",
  },
];

export const SAAY_TESTIMONIALS: Testimonial[] = [
  {
    id: "rev1",
    name: "مروة عبد الفتاح",
    role: "ولي أمر",
    location: "القاهرة الجديدة",
    countryFlag: "🇪🇬",
    curriculum: "المنهج المصري - لغات وثانوية عامة",
    grade: "ثالثة ثانوي",
    subject: "الفيزياء والرياضيات",
    rating: 5,
    content: "المعلم كان متمكناً جداً في شرح أفكار بنك الأسئلة والمسائل المركبة في الفيزياء والرياضيات لغات. وفر علينا ضياع الوقت في السناتر، وتقرير كل حصة كان يوضح نقاط القوة بوضوح.",
    improvementText: "ارتفعت درجة الطالبة إلى 96% في الامتحانات التجريبية",
  },
  {
    id: "rev2",
    name: "عبد الله النعيمي",
    role: "ولي أمر",
    location: "دبي",
    countryFlag: "🇦🇪",
    curriculum: "المنهج الإماراتي واختبارات EmSAT",
    grade: "الصف 12 - متقدم",
    subject: "الرياضيات و EmSAT",
    rating: 5,
    content: "سَعى وفرت لنا معلماً متخصصاً في المنهج الإماراتي المتقدم وامتحان EmSAT الرياضيات. الشرح الفردي والتركيز مع ابني رفع من ثقته وسرعته في حل المسائل بشكل ملحوظ.",
    improvementText: "حقق سكور 1650 في اختبار EmSAT الرياضيات",
  },
  {
    id: "rev3",
    name: "عمر الشناوي",
    role: "طالب",
    location: "الإسكندرية",
    countryFlag: "🇪🇬",
    curriculum: "المنهج البريطاني (IGCSE)",
    grade: "Year 11",
    subject: "Cambridge Chemistry & Biology",
    rating: 5,
    content: "كنت محتاج مراجعة مركزة على الـ Past Papers وطريقة الإجابة النموذجية في الكيمياء والأحياء. المعلمة شرحت كل جزئية في المارك سكيم وراجعت معايا كل الأخطاء السابقة.",
    improvementText: "حصل على تقدير 9 في امتحانات كامبريدج IGCSE",
  },
  {
    id: "rev4",
    name: "شيخة الكتبي",
    role: "طالبة",
    location: "أبوظبي",
    countryFlag: "🇦🇪",
    curriculum: "البكالوريا الدولية (IB DP)",
    grade: "DP2",
    subject: "Mathematics HL & Physics",
    rating: 5,
    content: "الدروس الفردية مع أستاذ عبد الرحمن ساعدتني جداً في فهم أفكار الـ Calculus وحسابات الـ IA في الفيزياء. التسجيلات كانت مرجع أساسي ليا قبل التقييم النهائي.",
    improvementText: "حصلت على الدرجة 7 في تقييم الرياضيات الدولي",
  },
];

export const SAAY_FAQS: FAQItem[] = [
  {
    id: "faq1",
    question: "ما هي الدول والمناهج التي تدعمها أكاديمية سَعى حالياً؟",
    answer: "نعمل حالياً بتركيز كامل وتغطية شاملة في جمهورية مصر العربية والإمارات العربية المتحدة؛ حيث نوفر نخبة المعلمين المعتمدين للمناهج الوطنية (المصري العام واللغات، والإماراتي بمساراته وامتحانات EmSAT) والمناهج الدولية (البريطاني IGCSE، الأمريكي SAT/EST، والبكالوريا الدولية IB).",
    category: "curriculum",
  },
  {
    id: "faq2",
    question: "كيف يتم اختيار واعتماد المعلمين في أكاديمية سَعى؟",
    answer: "نتبع في سَعى معايير فحص واختيار صارمة جداً في مصر والإمارات؛ حيث نقبل أقل من 5% من المتقدمين بعد التحقق الدقيق من مؤهلاتهم الأكاديمية وخبراتهم في كبرى المدارس، واجتياز اختبار تدريسي تفاعلي حقيقي ومقابلات تقييم الأسلوب والشغف التعليمي.",
    category: "teachers",
  },
  {
    id: "faq3",
    question: "هل الحصص تكون فردية أم جماعية؟",
    answer: "جميع حصص سَعى هي حصص فردية خاصة 1-on-1 (طالب واحد مع معلم واحد) لضمان التركيز الكامل بنسبة 100%، وتخصيص الشرح وسرعة التدريس وفق الاحتياج الفعلي للطالب دون أي تشتيت.",
    category: "booking",
  },
  {
    id: "faq4",
    question: "ماذا لو كنت أدرس في مدرسة تتبع نظاماً دراسياً خاصاً؟",
    answer: "في سَعى نؤمن بأن احتياج الطالب يأتي أولاً. يمكنك الضغط على 'طلب منسق أكاديمي' أو التواصل معنا عبر واتساب، وسيقوم فريق المنسقين الأكاديميين بتوفير معلم معتمد ومطابق لنظام مدرستك فوراً.",
    category: "curriculum",
  },
  {
    id: "faq5",
    question: "كيف يستطيع ولي الأمر متابعة مستوى ابنه؟",
    answer: "يحصل ولي الأمر على تقرير أداء تفصيلي بعد كل حصة يوضح مدى استيعاب الطالب، الواجبات، ونقاط القوة والتحسين، بالإضافة إلى إمكانية مشاهدة تسجيل الحصة بالكامل في أي وقت ومتابعة جدول الحصص القادمة.",
    category: "parents",
  },
  {
    id: "faq6",
    question: "ما هي سياسة الاسترداد وضمان الرضا؟",
    answer: "نحن نضمن رضاك التام عن التجربة التعليمية. إذا لم تكن راضياً عن الحصة الاستكشافية الأولى لأي سبب، نعيد لك المبلغ بالكامل أو نوفر لك حصة بديلة مع معلم آخر فوراً وبكل ترحيب.",
    category: "pricing",
  },
];
