import { Country, Curriculum, Subject, SubjectGroup, PricingPlan, Testimonial, FAQItem } from "@/types";

export const SAAY_COUNTRIES: Country[] = [
  {
    id: "egypt",
    name: "جمهورية مصر العربية",
    code: "EG",
    flag: "🇪🇬",
    curricula: ["national-eg", "languages-eg", "british", "american", "stem", "ib"],
  },
  {
    id: "uae",
    name: "الإمارات العربية المتحدة",
    code: "AE",
    flag: "🇦🇪",
    curricula: ["national-ae", "british", "american", "ib"],
  },
];

export const SAAY_CURRICULA: Curriculum[] = [
  {
    id: "national-eg",
    name: "المنهج المصري (العام واللغات والتجريبي)",
    enName: "Egyptian National & Languages Curriculum",
    description: "مقررات وزارة التربية والتعليم لجميع الصفوف الدراسية والتأسيس للشهادة الإعدادية والثانوية العامة",
    grades: ["المرحلة الابتدائية", "المرحلة الإعدادية", "المرحلة الثانوية"],
  },
  {
    id: "national-ae",
    name: "المنهج الإماراتي الوزاري واختبارات EmSAT",
    enName: "UAE Ministry Curriculum & EmSAT",
    description: "شامل مسارات التعليم العام والمتقدم وامتحانات قياس الكفاءة التربوية EmSAT",
    grades: ["الحلقة الأولى (1-4)", "الحلقة الثانية (5-8)", "الحلقة الثالثة (9-12)", "امتحانات EmSAT"],
  },
  {
    id: "british",
    name: "المنهج البريطاني (IGCSE / GCSE / A-Levels)",
    enName: "British Curriculum (Cambridge & Edexcel)",
    description: "شرح المناهج والتدريب على نماذج الامتحانات السابقة وحل أسئلة Past Papers",
    grades: ["Key Stage 3", "Year 10-11 (IGCSE)", "Year 12-13 (A-Levels)"],
  },
  {
    id: "american",
    name: "المنهج الأمريكي والدبلومة الأمريكية (SAT / EST)",
    enName: "American Diploma & SAT/EST",
    description: "تغطية مقررات الدبلومة الأمريكية والتدريب لاجتياز اختبارات SAT و EST و ACT",
    grades: ["Middle School", "High School (Grades 9-12)", "SAT & EST Prep"],
  },
];

export const SAAY_SUBJECTS: Subject[] = [
  { id: "math", name: "الرياضيات (Mathematics)", enName: "Mathematics", category: "math", iconName: "Calculator" },
  { id: "science", name: "العلوم والفيزياء والكيمياء", enName: "Science & Physics", category: "science", iconName: "Atom" },
  { id: "arabic", name: "اللغة العربية والنحو والبلاغة", enName: "Arabic", category: "languages", iconName: "BookOpen" },
  { id: "english", name: "اللغة الإنجليزية (English Language)", enName: "English", category: "languages", iconName: "BookA" },
  { id: "exam-prep", name: "اختبارات المعادلات (EmSAT / SAT / EST)", enName: "Standardized Tests", category: "exam-prep", iconName: "GraduationCap" },
];

export const SAAY_SUBJECT_GROUPS: SubjectGroup[] = [
  {
    id: "grp-math-eg-sec",
    subjectName: "الرياضيات (عام ولغات)",
    curriculumId: "national-eg",
    curriculumName: "المنهج المصري - المرحلة الإعدادية والثانوية",
    grade: "الشهادة الإعدادية والثانوية العامة",
    countryId: "egypt",
    sessionsPerMonth: 8,
    monthlyPrice: 250,
    pricePerSession: 31,
    currency: "ج.م",
    schedule: "مجموعتان متاحتان (السبت والثلاثاء 6:00 م) أو (الأحد والأربعاء 7:00 م)",
    seatsStatus: "متاح الانضمام للمجموعة القادمة",
    features: [
      "8 حصص شهرياً بمعدل حصتين أسبوعياً",
      "شرح وافٍ وتدريب مكثف على نماذج الامتحانات",
      "تسجيل كامل للحصة متاح للطالب وولي الأمر",
      "تنسيق ومتابعة مستمرة عبر واتساب",
      "معلم مصري تم اختباره وتأهيله بعناية لتدريس المجموعة",
    ],
  },
  {
    id: "grp-arabic-eg",
    subjectName: "اللغة العربية والنحو والبلاغة",
    curriculumId: "national-eg",
    curriculumName: "المنهج المصري - كافة المراحل",
    grade: "الابتدائي، الإعدادي، والثانوي",
    countryId: "egypt",
    sessionsPerMonth: 8,
    monthlyPrice: 250,
    pricePerSession: 31,
    currency: "ج.م",
    schedule: "مواعيد مرنة تناسب جدول الطالب",
    seatsStatus: "متاح الانضمام",
    features: [
      "8 حصص شهرياً بمعدل حصتين أسبوعياً",
      "تأسيس قوي في قواعد النحو والإعراب والبلاغة",
      "تسجيلات الحصص متاحة للمراجعة في أي وقت",
      "متابعة وتنسيق مباشر مع إدارة سَعى",
      "معلم متخصص ومختبر من إدارة سَعى",
    ],
  },
  {
    id: "grp-science-eg",
    subjectName: "العلوم والفيزياء والكيمياء",
    curriculumId: "national-eg",
    curriculumName: "المنهج المصري (عربي ولغات)",
    grade: "الإعدادي والثانوي",
    countryId: "egypt",
    sessionsPerMonth: 8,
    monthlyPrice: 250,
    pricePerSession: 31,
    currency: "ج.م",
    schedule: "مجموعات مسائية مريحة",
    seatsStatus: "متاح الانضمام",
    features: [
      "8 حصص شهرياً (حصتان أسبوعياً)",
      "تبسيط المفاهيم العلمية والتطبيق العملي للمسائل",
      "تسجيل كل حصة لمراجعة ليلة الامتحان",
      "متابعة مستمرة مع المنسق الأكاديمي",
    ],
  },
  {
    id: "grp-english-all",
    subjectName: "اللغة الإنجليزية والمناهج الدولية",
    curriculumId: "british",
    curriculumName: "المنهج المصري والبريطاني (IGCSE & General)",
    grade: "كافة المراحل الدراسية",
    countryId: "egypt",
    sessionsPerMonth: 8,
    monthlyPrice: 250,
    pricePerSession: 31,
    currency: "ج.م",
    schedule: "مواعيد أسبوعية منتظمة",
    seatsStatus: "متاح الانضمام",
    features: [
      "8 حصص شهرياً للمادة",
      "صقل مهارات القواعد، الكتابة، وفهم النصوص",
      "تدريب على نماذج الامتحانات السابقة",
      "متابعة مستمرة عبر واتساب",
    ],
  },
  {
    id: "grp-emsat-ae",
    subjectName: "مجموعات المنهج الإماراتي واختبارات EmSAT",
    curriculumId: "national-ae",
    curriculumName: "المنهج الإماراتي الوزاري وامتحانات إمسات",
    grade: "الحلقة 2 و 3 وطلاب الثانوية (EmSAT)",
    countryId: "uae",
    sessionsPerMonth: 8,
    monthlyPrice: 280,
    pricePerSession: 35,
    currency: "درهم",
    schedule: "مواعيد مسائية تناسب توقيت الإمارات",
    seatsStatus: "متاح الانضمام لطلاب الإمارات",
    features: [
      "8 حصص شهرياً (35 درهم للحصة ضمن الباقة)",
      "تغطية معايير المنهج الإماراتي أو اختبارات EmSAT",
      "تسجيل الحصص بالكامل بجودة فائقة",
      "متابعة وتنسيق مباشر مع ولي الأمر",
      "معلم مصري مختبر ومتمكن من المنهج الإماراتي",
    ],
  },
  {
    id: "grp-math-ae",
    subjectName: "الرياضيات والعلوم لطلاب الإمارات",
    curriculumId: "national-ae",
    curriculumName: "المنهج الإماراتي والمناهج الدولية الخاصة",
    grade: "الصفوف من 5 إلى 12",
    countryId: "uae",
    sessionsPerMonth: 8,
    monthlyPrice: 280,
    pricePerSession: 35,
    currency: "درهم",
    schedule: "مجموعات أسبوعية تفاعلية",
    seatsStatus: "متاح الانضمام",
    features: [
      "8 حصص شهرياً بمعدل حصتين في الأسبوع",
      "شرح تفاعلي وتبسيط للمسائل والنظريات",
      "تسجيل الحصص وإتاحتها للمراجعة",
      "إشراف أكاديمي مباشر من سَعى",
    ],
  },
];

// Egypt Pricing Plans (250 EGP/month for 8 sessions per subject)
export const SAAY_PRICING_PLANS_EG: PricingPlan[] = [
  {
    id: "trial-eg",
    name: "الحصة الاستكشافية الأولى",
    subtitle: "حصة أولى للتعرف على طريقة الشرح وتجربة المنصة",
    pricePerSession: 40,
    totalPrice: 40,
    currency: "ج.م",
    sessionsCount: 1,
    features: [
      "حصة استكشافية كاملة للمادة المطلوبة",
      "التعرف على أسلوب الشرح والتفاعل",
      "تسجيل الحصة بالكامل بجودة فائقة",
      "تنسيق المواعيد مع المنسق الأكاديمي",
      "ضمان استرداد الرسوم إن لم تناسبك الحصة",
    ],
    ctaText: "احجز حصتك الاستكشافية (40 ج.م)",
  },
  {
    id: "growth-eg",
    name: "اشتراك المادة الشهري (8 حصص)",
    subtitle: "الاشتراك الأساسي للمادة بمعدل حصتين أسبوعياً",
    badge: "الخيار الأفضل للمادة شهرياً",
    pricePerSession: 31,
    totalPrice: 250,
    currency: "ج.م",
    sessionsCount: 8,
    popular: true,
    features: [
      "8 حصص شهرياً للمادة (حصتان أسبوعياً)",
      "شرح المنهج والمتابعة والواجبات خطوة بخطوة",
      "معلم مصري تم اختباره وتأهيله بعناية من سَعى",
      "تسجيل جميع الحصص للرجوع إليها ليلة الامتحان",
      "جدول أسبوعي منتظم ومتابعة مستمرة عبر واتساب",
      "ضمان استرداد الرسوم في حال عدم الرضا",
    ],
    ctaText: "اشترك في باقة المادة (250 ج.م)",
  },
  {
    id: "mastery-eg",
    name: "اشتراك الفصل الدراسي كاملاً",
    subtitle: "تغطية المادة طوال الترم مع مراجعات الامتحانات النهائية",
    badge: "أعلى توفير للترم",
    pricePerSession: 28,
    totalPrice: 690,
    currency: "ج.م",
    sessionsCount: 24,
    features: [
      "24 حصة تغطي الفصل الدراسي كاملاً",
      "مراجعات نهائية وحل نماذج الامتحانات السابقة",
      "تسجيلات دائمة لجميع الحصص طوال الفصل الدراسي",
      "متابعة مستمرة مع المنسق الأكاديمي",
      "أولوية في مواعيد المراجعات قبل الامتحانات",
    ],
    ctaText: "اشترك في باقة الترم (690 ج.م)",
  },
];

// UAE Pricing Plans (approx 30-50 AED per session, 280 AED/month for 8 sessions)
export const SAAY_PRICING_PLANS_AE: PricingPlan[] = [
  {
    id: "trial-ae",
    name: "الحصة الاستكشافية الأولى",
    subtitle: "حصة أولى للتعرف على طريقة الشرح وتجربة المنصة",
    pricePerSession: 35,
    totalPrice: 35,
    currency: "درهم",
    sessionsCount: 1,
    features: [
      "حصة استكشافية كاملة للمادة المطلوبة",
      "التعرف على أسلوب الشرح والتفاعل",
      "تسجيل الحصة بالكامل بجودة فائقة",
      "تنسيق المواعيد مع المنسق الأكاديمي",
      "ضمان استرداد الرسوم إن لم تناسبك الحصة",
    ],
    ctaText: "احجز حصتك الاستكشافية (35 درهم)",
  },
  {
    id: "growth-ae",
    name: "اشتراك المادة الشهري (8 حصص)",
    subtitle: "الاشتراك الأساسي للمادة بمعدل حصتين أسبوعياً",
    badge: "الاشتراك الشهري الأكثر طلباً في الإمارات",
    pricePerSession: 35,
    totalPrice: 280,
    currency: "درهم",
    sessionsCount: 8,
    popular: true,
    features: [
      "8 حصص شهرياً للمادة (35 درهم للحصة)",
      "تغطية المنهج الإماراتي أو اختبارات EmSAT أو المناهج الدولية",
      "معلم مصري مؤهل ومختبر لتدريس المنهج",
      "تسجيل جميع الحصص للرجوع إليها في أي وقت",
      "جدول أسبوعي منتظم ومتابعة مستمرة عبر واتساب",
      "ضمان استرداد الرسوم في حال عدم الرضا",
    ],
    ctaText: "اشترك في باقة المادة (280 درهم)",
  },
  {
    id: "mastery-ae",
    name: "اشتراك الفصل الدراسي كاملاً",
    subtitle: "تغطية شاملة للمنهج ومراجعات مكثفة قبل الاختبارات النهائية",
    badge: "أعلى توفير فصلي",
    pricePerSession: 31,
    totalPrice: 760,
    currency: "درهم",
    sessionsCount: 24,
    features: [
      "24 حصة تغطي الفصل الدراسي كاملاً",
      "مراجعات مكثفة وتدريب على نماذج الامتحانات و EmSAT",
      "تسجيل كامل لكافة الحصص طوال الترم",
      "متابعة وتنسيق مباشر مع فريق سَعى عبر واتساب",
      "أولوية في مواعيد المراجعات قبل الامتحانات",
    ],
    ctaText: "اشترك في باقة الترم (760 درهم)",
  },
];

export const SAAY_PRICING_PLANS = SAAY_PRICING_PLANS_EG;

export const SAAY_TESTIMONIALS: Testimonial[] = [
  {
    id: "rev1",
    name: "مروة عبد الفتاح",
    role: "ولي أمر",
    location: "القاهرة",
    countryFlag: "🇪🇬",
    curriculum: "المنهج المصري - لغات",
    grade: "الصف الثالث الإعدادي",
    subject: "الرياضيات والعلوم",
    rating: 5,
    content: "اشتراك المادة بـ 250 جنيه لـ 8 حصص شهرياً وفر علينا تعب السناتر والمصاريف الكبيرة، الشرح مبسط والمواعيد منتظمة والتسجيلات بتساعد ابني يراجع في أي وقت.",
    improvementText: "تفوق ملحوظ في درجات امتحانات الشهور",
  },
  {
    id: "rev2",
    name: "عبد الله النعيمي",
    role: "ولي أمر",
    location: "دبي",
    countryFlag: "🇦🇪",
    curriculum: "المنهج الإماراتي و EmSAT",
    grade: "الصف 12 - متقدم",
    subject: "الرياضيات و EmSAT",
    rating: 5,
    content: "المعلم المصري اللي حددته سَعى لمجموعة ابني ممتاز جداً في تبسيط مسائل إمسات الرياضيات وبسعر مناسب جداً (35 درهم للحصة). المتابعة والتسجيلات سهلت علينا المراجعة.",
    improvementText: "اجتياز اختبار EmSAT بنجاح",
  },
  {
    id: "rev3",
    name: "هاني محمود",
    role: "ولي أمر",
    location: "الجيزة",
    countryFlag: "🇪🇬",
    curriculum: "المنهج المصري - عام",
    grade: "أولى ثانوي",
    subject: "الفيزياء والكيمياء",
    rating: 5,
    content: "كنت قلقان في الأول من فكرة الأونلاين، بس لما جربنا الحصة الاستكشافية وشفت التفاعل وحل التمارين والتسجيل، اشتركنا علطول في الباقة الشهرية.",
    improvementText: "ارتفاع درجات الطالب وفهم النظريات بسهولة",
  },
];

export const SAAY_FAQS: FAQItem[] = [
  {
    id: "faq1",
    question: "كيف يتم حجز المادة وتحديد المجموعات في سَعى؟",
    answer: "الأمر في غاية البساطة: تختار دولتك (مصر أو الإمارات) ثم المنهج والصف والمادة التي تريد دراستها، وتحدد الموعد الأنسب. سَعى تقوم بتنظيم المجموعة الدراسية وتعيين المعلم المؤهل والمختبر لتدريس المجموعة ومتابعة الطلاب خطوة بخطوة.",
    category: "booking",
  },
  {
    id: "faq2",
    question: "كم تكلفة الاشتراك للطلاب في مصر والإمارات؟",
    answer: "في مصر، سعر اشتراك المادة الواحدة هو 250 جنيهاً مصرياً شهرياً (يشمل 8 حصص بمعدل حصتين أسبوعياً). وفي الإمارات، تتراوح تكلفة الحصة بين 30 إلى 50 درهماً (أو 280 درهماً للباقة الشهرية المكونة من 8 حصص).",
    category: "pricing",
  },
  {
    id: "faq3",
    question: "من هم معلمو سَعى وكيف يتم اختيارهم؟",
    answer: "معلمو سَعى هم نخبة من الكفاءات والمعلمين المصريين الشغوفين. نقوم باختبارهم بعناية والتأكد من أسلوب شرحهم وتمكنهم من المنهج قبل تعيينهم لتدريس أي مجموعة دراسية لضمان تجربة تعليمية ممتعة ومفيدة.",
    category: "teachers",
  },
  {
    id: "faq4",
    question: "كيف يستطيع الطالب مراجعة الدروس السابقة؟",
    answer: "يتم تسجيل جميع الحصص التفاعلية بالكامل وإتاحتها للطالب وولي الأمر للرجوع إليها في أي وقت لمراجعة المسائل والمفاهيم ليلة الاختبارات وتثبيت المعلومة.",
    category: "parents",
  },
  {
    id: "faq5",
    question: "ماذا لو لم تنل الحصة الأولى إعجابنا؟",
    answer: "نحن نضمن رضاك تماماً. إذا جربت الحصة الاستكشافية الأولى وشعرت أنها غير مناسبة لابنك، نعيد لك رسوم الحصة كاملة فوراً وبدون أي شروط.",
    category: "pricing",
  },
  {
    id: "faq6",
    question: "كيف ينضم المعلمون المصريون إلى سَعى؟",
    answer: "نرحب بالمعلمين المصريين المؤهلين. بعد تقديم الطلب واجتياز اختبار التقييم التدريسي، يتم إسناد المجموعات الدراسية للمعلم مع عائد مجزي يتراوح بين 100 إلى 150 جنيهاً مصرياً للساعة مع تحويلات مالية منتظمة ومرونة في الأوقات.",
    category: "teachers",
  },
];
